### ISSUE TITLE
Breaks with Rails 4.1

### ISSUE THREAD

**Issue by alexpeattie** [makandra/dusen#4]
The gem seems to break with Rails 4.1. I think the issue lies with use of the `scoped` method, which is deprecated in Rails 4 and removed completely in Rails 4.1:

https://github.com/makandra/dusen/blob/master/lib/dusen/active_record/base_ext.rb#L13

https://github.com/rails/rails/commit/b343abd87517a367e6085b674de2477649de6365

**Comment by codener** [comment]
Confirming Dusen is working with Rails 4.2 and [`edge_rider`](/makandra/edge_rider) 0.3.1.
