### ISSUE TITLE
Case insensitive search on string and text

### ISSUE THREAD

**Issue by SaimonL** [makandra/dusen#7]
This is more like a feature. 
Is there a way to do a case insensitive search on string and text?
Thanks in advance.

**Comment by henning-koch** [comment]
I'm fairly certain that all Dusen searches are insensitive to case?

**Comment by SaimonL** [comment]
Woops I meant case insensitive. I think the case insensitive search is not working for me because of the way mysql database was created.

**Comment by henning-koch** [comment]
Since Dusen is just a wrapper around MySQL: You can do case-sensitive searches by using a case-sensitive collation for the indexed columns. Note that this will also change the case sensitivity of other MySQL operators like `=` or `IN`.
